# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'krooqi' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for krooqi
  pod 'MobileCenter/Crashes', '~> 0.13.0'
  pod 'MobileCenter/Analytics', '~> 0.13.0'
  pod 'RNMobileCenterShared', '~> 0.10.0'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'

  

  target 'krooqiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'krooqi-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for krooqi-tvOS

  target 'krooqi-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
